pr:
  autoCancel: "true"
  branches:
    include:
    - DevOps
    - main
  paths:
    exclude:
    - README.md
    - azure-pipelines.yml
stages:
- stage: TestSalesforceOrg
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/DevOps'))
  jobs:
  - job: DeployTestOrg
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
          checkLatest: true
      - bash: 
          npm install sfdx-cli --global
        displayName: Install Salesforce CLI
      - bash:
            sfdx config:set restDeploy=false --global
        displayName: Use SOAP API for Deployment
      - bash:
            sfdx force:auth:jwt:grant --clientid 3MVG9pRzvMkjMb6kcWEfrdtzId2Wi.FimEeNrd4yPap3Bp7otgVtIZkGcbiadmwXkRZ3dClT3Bww.KbExZTZX --jwtkeyfile ./bin/server.key --username podili.aseesh@collaberadigital.com --instanceurl https://login.salesforce.com
        displayName: Authorize Salesforce DeployTestOrg Org
      - bash:
            sfdx force:source:deploy -p force-app -w 10 -u podili.aseesh@collaberadigital.com
        displayName: Deploy source code to DeployTestOrg Org
